### ISSUE TITLE
Cannot find where to submit results

### ISSUE THREAD

**Issue by TanWenCong00** [Neuron-Hackathon/neuron_hackathon_2022#5]
Hi! Not sure where to get help but this was the only channel I could find. 
I was trying to submit some results but I'm not sure where I should do it. I have tried navigating to this page (see below)
![image](https://user-images.githubusercontent.com/105650536/195975297-c63f3776-58e2-405d-ba2b-dee9b48694db.png)
However, it does not seem to allow me to submit through that page. Where should I go to submit results? Thank you!

Edit: Not sure if this affects anything, but I'm participating as an individual (i.e. there's only 1 member in my group), but from #2 , I saw that it should not be a problem.

**Comment by Neuron-Hackathon** [comment]
The game began at UTC+8 16:00 p.m. , the submission tab should be activated now
<img width="709" alt="Screenshot 2022-10-15 at 4 48 56 PM" src="https://user-images.githubusercontent.com/113485775/195977925-0d980d38-fe94-49ca-aa76-1c6c9cb136a8.png">

**Comment by TanWenCong00** [comment]
Works now, thanks!
