### ISSUE TITLE
What happens when the van attempts to retrieve a scooter but there is none in the grid?

### ISSUE THREAD

**Issue by chienshyong** [Neuron-Hackathon/neuron_hackathon_2022#6]

**Comment by Neuron-Hackathon** [comment]
No scooter can be retrieved when the van attempts to retrieve a scooter but there is none in the grid.

**Comment by chienshyong** [comment]
Will it invalidate the shift plan if it is attempted? What happens the instruction is to fetch one from A and deposit at B, but there is none at A? Will the van continue to B but not deposit any scooter?

**Comment by Neuron-Hackathon** [comment]
It will not invalidate the shift plan.
In round 1, you can assume there are some spare scooters in the van to cover these edge cases (so you still can deploy at B). But you can't assume unlimited spare scooters to do all deployment without retrieval. If you do so, your shift plan will not satisfy the permit cap requirement.
