### ISSUE TITLE
Question about the priority of action

### ISSUE THREAD

**Issue by EvelynNeverGiveUp** [Neuron-Hackathon/neuron_hackathon_2022#7]
What happens when there is only one e-scooter and the van attempts to retrieve a scooter and user want to start a trip at the same time?

**Comment by EvelynNeverGiveUp** [comment]
A shift scheduled to start at 9:00 is considered to be completed immediately at 9:00 or the retrieve and deploy action are completed one by one over time?

**Comment by Neuron-Hackathon** [comment]
If user attempt and van attempt happen at the same time, we assume user attempt first.

All shift actions in a given hour are only effective at the beginning of the next hour. In your example, a shift scheduled to start at 9 is considered to be completed at 09:59 and effective at 10:00.
